2025-06-04 18:03:51,501 ERROR: Exception on /user/Владимир [GET] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\myblog\app\routes.py", line 121, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url, list_followers=list_followers, list_following=list_following)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\myblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\myblog\app\templates\base.html", line 58, in top-level template code
    {% block content %}{% endblock %}
  File "D:\myblog\app\templates\user.html", line 18, in block 'content'
    {{ form.hidden_tag() }}
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-06-04 18:04:36,950 ERROR: Exception on /user/Владимир [GET] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\myblog\app\routes.py", line 121, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url, list_followers=list_followers, list_following=list_following)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\myblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\myblog\app\templates\base.html", line 58, in top-level template code
    {% block content %}{% endblock %}
  File "D:\myblog\app\templates\user.html", line 18, in block 'content'
    {{ form.hidden_tag() }}
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-06-04 18:04:41,900 ERROR: Exception on /user/McLovin [GET] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\myblog\app\routes.py", line 121, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url, list_followers=list_followers, list_following=list_following)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\myblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\myblog\app\templates\base.html", line 58, in top-level template code
    {% block content %}{% endblock %}
  File "D:\myblog\app\templates\user.html", line 18, in block 'content'
    {{ form.hidden_tag() }}
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-06-04 18:19:54,080 INFO: Myblog startup [in D:\myblog\app\__init__.py:71]
2025-06-04 19:18:14,848 INFO: Myblog startup [in D:\myblog\app\__init__.py:76]
2025-06-04 19:25:13,177 INFO: Myblog startup [in D:\myblog\app\__init__.py:76]
2025-06-05 01:32:13,050 INFO: Myblog startup [in D:\myblog\app\__init__.py:76]
