2025-05-25 21:08:12,446 INFO: Myblog startup [in D:\myblog\app\__init__.py:59]
2025-05-25 21:11:51,492 INFO: Myblog startup [in D:\myblog\app\__init__.py:59]
2025-05-25 21:13:20,886 INFO: Myblog startup [in D:\myblog\app\__init__.py:59]
2025-05-25 21:25:02,603 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
2025-05-25 21:51:08,493 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
2025-05-25 21:53:01,937 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
2025-05-25 21:53:04,879 ERROR: Exception on /user/јлександр [GET] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\myblog\app\routes.py", line 120, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url, list_followers=list_followers, list_following=list_following)
NameError: name 'list_followers' is not defined
2025-05-25 21:55:19,860 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
2025-05-25 22:59:19,883 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
2025-05-25 22:59:32,574 ERROR: Exception on /reset_password_request [POST] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\myblog\app\routes.py", line 203, in reset_password_request
    send_password_reset_email(user)
  File "D:\myblog\app\email.py", line 17, in send_password_reset_email
    token = user.get_reset_password_token()
  File "D:\myblog\app\models.py", line 90, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')    # utf-8 - специально дл€ приложени€ (токен в виде послед. байтов)
AttributeError: 'str' object has no attribute 'decode'
2025-05-25 23:01:01,222 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
2025-05-25 23:01:12,094 ERROR: Exception on /reset_password_request [POST] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\myblog\app\routes.py", line 203, in reset_password_request
    send_password_reset_email(user)
  File "D:\myblog\app\email.py", line 21, in send_password_reset_email
    text_body=render_template('email/reset_password.txt', user=user, token=token),
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "d:\myblog\myenv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2025-05-25 23:04:49,579 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
2025-05-25 23:04:57,671 ERROR: Exception on /reset_password_request [GET] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\myblog\app\routes.py", line 206, in reset_password_request
    return render_template('reset_password_request.html', title='—брс парол€', form=form)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "d:\myblog\myenv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: reset_password_request.html
2025-05-25 23:05:29,097 INFO: Myblog startup [in D:\myblog\app\__init__.py:62]
2025-05-25 23:05:37,862 ERROR: Exception on /reset_password_request [POST] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\myblog\app\routes.py", line 203, in reset_password_request
    send_password_reset_email(user)
  File "D:\myblog\app\email.py", line 22, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "d:\myblog\myenv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\myblog\app\templates\email\reset_password.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\myblog\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "D:\myblog\app\templates\email\reset_password.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "d:\myblog\myenv\lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
