2025-06-05 19:22:06,973 ERROR: Exception on / [GET] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
  File "d:\myblog\myenv\lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "d:\myblog\myenv\lib\site-packages\flask\helpers.py", line 262, in url_for
    **values,
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2028, in url_for
    force_external=_external,
  File "d:\myblog\myenv\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2025-06-05 19:41:16,060 INFO: Myblog startup [in D:\myblog\app\__init__.py:74]
2025-06-05 19:41:18,459 ERROR: Exception on / [GET] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
  File "d:\myblog\myenv\lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "d:\myblog\myenv\lib\site-packages\flask\helpers.py", line 262, in url_for
    **values,
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2028, in url_for
    force_external=_external,
  File "d:\myblog\myenv\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2025-06-05 20:17:15,134 INFO: Myblog startup [in D:\myblog\app\__init__.py:74]
2025-06-05 20:17:18,220 ERROR: Exception on / [GET] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
  File "d:\myblog\myenv\lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "d:\myblog\myenv\lib\site-packages\flask\helpers.py", line 262, in url_for
    **values,
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2028, in url_for
    force_external=_external,
  File "d:\myblog\myenv\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2025-06-05 20:20:06,451 INFO: Myblog startup [in D:\myblog\app\__init__.py:74]
2025-06-05 20:20:09,110 ERROR: Exception on / [GET] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
  File "d:\myblog\myenv\lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "d:\myblog\myenv\lib\site-packages\flask\helpers.py", line 262, in url_for
    **values,
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2028, in url_for
    force_external=_external,
  File "d:\myblog\myenv\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2025-06-05 21:36:12,457 INFO: Myblog startup [in D:\myblog\app\__init__.py:74]
2025-06-05 21:36:29,785 INFO: Myblog startup [in D:\myblog\app\__init__.py:74]
2025-06-05 21:36:39,886 INFO: Myblog startup [in D:\myblog\app\__init__.py:74]
2025-06-05 21:37:45,488 INFO: Myblog startup [in D:\myblog\app\__init__.py:74]
2025-06-05 21:37:48,937 ERROR: Exception on / [GET] [in d:\myblog\myenv\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
  File "d:\myblog\myenv\lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "d:\myblog\myenv\lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "d:\myblog\myenv\lib\site-packages\flask\helpers.py", line 262, in url_for
    **values,
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "d:\myblog\myenv\lib\site-packages\flask\app.py", line 2028, in url_for
    force_external=_external,
  File "d:\myblog\myenv\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2025-06-05 21:43:52,229 INFO: Myblog startup [in D:\myblog\app\__init__.py:74]
